-- 充值订单表
-- Run in Supabase Dashboard -> SQL Editor

create table if not exists topup_orders (
  id bigint generated by default as identity primary key,
  user_id text not null,
  order_no text not null unique,
  amount integer not null,
  coins integer not null,
  status text not null default 'pending' check (status in ('pending', 'completed', 'failed')),
  method text not null default 'wechat',
  transaction_id text,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

-- 创建索引
create index if not exists topup_orders_user_id_idx on topup_orders(user_id);
create index if not exists topup_orders_order_no_idx on topup_orders(order_no);
create index if not exists topup_orders_status_idx on topup_orders(status);

-- RLS
alter table topup_orders enable row level security;

create policy "service role can do anything with topup_orders"
  on topup_orders for all
  using (true)
  with check (true);
