-- 交易记录表
-- Run in Supabase Dashboard -> SQL Editor

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null check (type in ('recharge', 'expense')),
  amount integer not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

-- 创建索引
create index if not exists transactions_user_id_idx on transactions(user_id);
create index if not exists transactions_created_at_idx on transactions(created_at desc);

-- RLS
alter table transactions enable row level security;

create policy "users can view own transactions"
  on transactions for select
  using (auth.uid()::text = user_id);

create policy "service role can insert transactions"
  on transactions for insert
  with check (true);
